services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npx prisma migrate deploy
    startCommand: node --env-file=.env ./backend/src/server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_tI9cZ4bqHVpl@ep-restless-bonus-a8zbq4ui-pooler.eastus2.azure.neon.tech/imjuverconecta?sslmode=require
      - key: NODE_ENV
        value: production
